@server = http://localhost:3000

### 회원 가입
POST {{server}}/auth/register
Content-Type: application/json

{
    "username": "Lee",
    "password": "Ttest1234",
    "email": "test@naver.com",
    "confirmPassword": "Ttest1234"
}

### 로그인
POST {{server}}/auth/login
Content-Type: application/json

{
    "email": "test@naver.com",
    "password": "Ttest1234"
}

### 프로필
POST  {{server}}/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkxlZSIsInJvbGVzIjpbInVzZXIiXSwic3ViIjoiNjUyOTEzNjY3NDMyOTJkNDI3NzZjMjRjIiwiaWF0IjoxNjk3MjI0MDYxLCJleHAiOjE2OTcyMjU4NjF9.wvLv9H7zrfjzJODW_P1aPNFlSmUWHXtoA62NmPBqjSw

### 리프레쉬 토큰 쿠키 테스트
POST  {{server}}/auth/refreshToken
Content-Type: application/json
credentials: 'include'

### 로그아웃
POST {{server}}/auth/logout
Content-Type: application/json