@server = http://localhost:3000

### 회원 가입
POST {{server}}/auth/register
Content-Type: application/json

{
    "username": "Lee",
    "password": "Ttest1234",
    "email": "test@naver.com",
    "confirmPassword": "Ttest1234"
}

### 로그인
POST {{server}}/auth/login
Content-Type: application/json

{
    "email": "tt@naver.com",
    "password": "qQwer1234"
}

### 프로필
GET  {{server}}/auth/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iu2VmOydtOyaqSIsInJvbGVzIjpbInVzZXIiXSwiYXZhdGFyIjoiIiwic3ViIjoiNjUzNDkyYzcwOTViZjFmMWY4YTllMjUyIiwiaWF0IjoxNjk3OTQ4Njg2LCJleHAiOjE2OTc5NTA0ODZ9.QgXLevVzcx_bPp99xno4TKaWVRox3_qkD8-ZH058p8M

### 리프레쉬 토큰 쿠키 테스트
POST  {{server}}/auth/refreshToken
Content-Type: application/json
credentials: 'include'

### 로그아웃
POST {{server}}/auth/logout
Content-Type: application/json

### 아바타 업데이트

PATCH {{server}}/auth/avatar
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Iu2VmOydtOyaqSIsInJvbGVzIjpbInVzZXIiXSwiZW1haWwiOiJ0dEBuYXZlci5jb20iLCJhdmF0YXIiOiIiLCJzdWIiOiI2NTM0OTJjNzA5NWJmMWYxZjhhOWUyNTIiLCJpYXQiOjE2OTc5NDkyNzYsImV4cCI6MTY5Nzk1MTA3Nn0.RthSeBOULzUXYo_sbvTpZeWfOpXhSj1DB-TsOelrpjs

{
    "avatar": "남자"
}